apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:

---        
apiVersion: v1
kind: Service
metadata:
  name: camera-service
  labels:
    run: camera
spec:
  type: NodePort
  clusterIP: 10.96.2.2
  ports:
  - name: rtsp 
    port: 554
    targetPort: 8554
    nodePort: 30554
    protocol: TCP
  - name: rtp
    port: 8000
    targetPort: 8050
    protocol: UDP
  - name: rtcp
    port: 8001
    targetPort: 8051
    protocol: UDP
  selector:
    app: camera

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
  labels:
    app: camera
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
        
    spec:
      initContainers:
        - name: init
          image: init:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
              - ALL
            privileged: false

      containers:

        - name: proxy
          image: rtsp-sidecar-proxy:latest
          imagePullPolicy: Never
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
            - name: rtp
              protocol: UDP
              containerPort: 8050
            - name: rtcp
              protocol: UDP
              containerPort: 8051
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1337
            runAsGroup: 1337
            privileged: false
          volumeMounts:
            - name: proxy-config
              mountPath: /tmp

        - name: rtsp
          image: aler9/rtsp-simple-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RTSP_RTSPPORT
              value: "554"
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 554
            - name: rtp
              protocol: UDP
              containerPort: 8000
            - name: rtcp
              protocol: UDP
              containerPort: 8001

        - name: ffmpeg
          image: ffmpeg-image
          imagePullPolicy: Never

      volumes:
        - name: proxy-config
          configMap:
            name: proxy-cfg
