---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facemask
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facemask
  template:
    metadata:
      labels:
        app: facemask
    spec:
      containers:
        - name: facemask 
          image: facemask-detector:latest
          imagePullPolicy: Never
          env:
            - name: RTSP_TRANSPORT
              value: "tcp"
            - name: INPUT_RTSP_URL
              value: "rtsp://10.244.0.11:554/mystream"  
            - name: OUTPUT_RTSP_URL
              value: "rtsp://10.96.3.3:554/mystream"  
