apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
spec:
  containers:
    - name: ffmpeg
      image: linuxserver/ffmpeg:latest
      imagePullPolicy: IfNotPresent
      command: ["ffmpeg"]
      args: ["-re", "-stream_loop", "-1", "-i", "/tmp/file.ts", "-c", "copy", "-f", "rtsp", "rtsp://10.96.2.2:554/mystream"]
      volumeMounts:
        - name: filets
          mountPath: /tmp/file.ts
    - name: proxy
      image: rtsp-sidecar-proxy:latest
      imagePullPolicy: Never
      ports:
        - name: rtsp
          protocol: TCP
          containerPort: 8554
        - name: rtp
          protocol: UDP
          containerPort: 8050
        - name: rtcp
          protocol: UDP
          containerPort: 8051
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1337
        runAsGroup: 1337
        privileged: false
      volumeMounts:
         - name: proxy-config
           mountPath: /tmp
  volumes:
    - name: filets
      hostPath:
        path: /tmp/file.ts
    - name: proxy-config
      configMap:
        name: proxy-cfg
