kind: Service
apiVersion: v1
metadata:
  name: k8s-apiclient-service
spec:
  selector:
    app: k8s-apiclient
  ports:
    - protocol: TCP
      port: 9899
      targetPort: 9898

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-apiclient-deployment
spec:
  selector:
    matchLabels:
      app: k8s-apiclient
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-apiclient

    spec:
      containers:
        - name: k8s-apiclient
          image: chartsoo/k8s-apiclient:latest
          imagePullPolicy: Always
