---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:
---
apiVersion: v1
kind: Pod
metadata:
  name: vlc 
  namespace: default
spec:
  initContainers:
    - name: init
      image: init:latest
      imagePullPolicy: Never
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - NET_ADMIN
          - NET_RAW
          drop:
          - ALL
        privileged: false
  containers:

    - name: proxy
      image: rtsp-sidecar-proxy:latest
      imagePullPolicy: Never
      ports:
        - name: rtsp
          protocol: TCP
          containerPort: 8554
        - name: rtp
          protocol: UDP
          containerPort: 8050
        - name: rtcp
          protocol: UDP
          containerPort: 8051
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1337
        runAsGroup: 1337
        privileged: false
      volumeMounts:
         - name: proxy-config
           mountPath: /tmp

    - name: vlc
      image: galexrt/vlc:latest
      imagePullPolicy: IfNotPresent
      command: ["cvlc"]
      args: ["-vvv", "--no-video", "rtsp://10.96.2.2:554/mystream"]

  volumes:
    - name: proxy-config
      configMap:
        name: proxy-cfg
